### ISSUE TITLE
I'm not able to find asset folder which contains Icons

### ISSUE THREAD

**Issue by gururajjeerge** [yhenni1989/med-i#4]
cloned git repo and installed all dependencies related 
Started project 

Unable to resolve module `../../../assets/Icons` from `/Users/gururajjeerge/Practice/med-i/src/components/MindScreen/index.js`: The module `../../../assets/Icons` could not be found from `/Users/gururajjeerge/Practice/med-i/src/components/MindScreen/index.js`. Indeed, none of these files exist:
  * `/Users/gururajjeerge/Practice/med-i/assets/Icons(.native||.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.svg|.native.svg|.svg|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.json|.native.json|.json)`
  * `/Users/gururajjeerge/Practice/med-i/assets/Icons/index(.native||.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.svg|.native.svg|.svg|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.json|.native.json|.json)`

ABI35_0_0RCTFatal
__37-[ABI35_0_0RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

**Comment by yhenni1989** [comment]
Sorry, but we decided not to share the assets. We only decided to share the code. If you want to have a feel of the app flow try the following Expo link: https://expo.io/@jones1989/med-i
